name: Static Analysis

on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run Static Analysis
        run: ./vendor/bin/phpstan analyse
